import type { VideoInfo } from "../services/api";

type Props = {
  video: VideoInfo;
  summary: string;
};

export default function PdfTemplate({ video, summary }: Props) {
  return (
    <div
      id="pdf-template"
      className="w-[794px] bg-white p-10 text-gray-900"
    >
      {/* Header */}

      <div className="border-b-4 border-blue-600 pb-6">
        <h1 className="text-4xl font-extrabold text-blue-700">
          BriefTube
        </h1>

        <p className="mt-2 text-lg text-gray-500">
          AI YouTube Summary Report
        </p>
      </div>

      {/* Thumbnail */}

      <img
        src={video.thumbnail}
        alt={video.title}
        className="mt-8 h-72 w-full rounded-xl object-cover"
      />

      {/* Video */}

      <h2 className="mt-8 text-3xl font-bold">
        {video.title}
      </h2>

      <p className="mt-2 text-lg text-gray-600">
        📺 {video.channel}
      </p>

      <p className="mt-2 text-sm text-gray-500">
        Generated on {new Date().toLocaleDateString()}
      </p>

      {/* Summary */}

      <div className="mt-10 rounded-xl bg-blue-50 p-8">
        <h3 className="mb-5 text-2xl font-bold text-blue-700">
          Summary
        </h3>

        <pre className="whitespace-pre-wrap font-sans leading-8">
          {summary}
        </pre>
      </div>

      {/* Footer */}

      <div className="mt-12 border-t pt-5 text-center text-sm text-gray-500">
        Generated by BriefTube

        <br />

        https://brief-tube-frontend.vercel.app
      </div>
    </div>
  );
}